// FRUIT TYPE
export const SWITCH_LOGIA = "SWITCH_LOGIA";
export const SWITCH_PARAMECIA = "SWITCH_PARAMECIA";
export const SWITCH_ZOAN = "SWITCH_ZOAN";

// NAV ITEM
export const SWITCH_LOGO = "SWITCH_LOGO";
export const SWITCH_FRUITS = "SWITCH_FRUITS";
export const SWITCH_CART = "SWITCH_CART";
export const SWITCH_LOGIN = "SWITCH_LOGIN";
export const SWITCH_REGISTER = "SWITCH_REGISTER";

// FRUITS
export const FETCH_FRUITS_BEGIN = "FETCH_FRUITS_BEGIN";
export const FETCH_FRUITS_SUCCESS = "FETCH_FRUITS_SUCCESS";
export const FETCH_FRUITS_FAIL = "FETCH_FRUITS_FAIL";

// CART
export const ADD_FRUIT = "ADD_FRUIT";
export const REMOVE_FRUIT = "REMOVE_FRUIT";
export const ADD_FRUIT_AMT = "ADD_FRUIT_AMT";
export const REMOVE_FRUIT_AMT = "REMOVE_FRUIT_AMT";

// AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
