// FRUIT TYPE
export const SWITCH_LOGIA = "SWITCH_LOGIA";
export const SWITCH_PARAMECIA = "SWITCH_PARAMECIA";
export const SWITCH_ZOAN = "SWITCH_ZOAN";

// NAV ITEM
export const SWITCH_LOGO = "SWITCH_LOGO";
export const SWITCH_FRUITS = "SWITCH_FRUITS";
export const SWITCH_CART = "SWITCH_CART";
export const SWITCH_LOGIN = "SWITCH_LOGIN";
export const SWITCH_REGISTER = "SWITCH_REGISTER";

// FRUITS
export const ADD_LOGIA = "ADD_LOGIA";
